# serverless.yml

service: apollo-lambda
provider:
  name: aws
  runtime: nodejs14.x
  stage: beta
  region: us-west-2
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true